# Generated by Django 5.0.2 on 2024-04-18 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('artist', models.CharField(max_length=200)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('song_file', models.FileField(blank=True, default=None, null=True, upload_to='songs/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='images/')),
                ('customer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='song.customer')),
                ('song', models.ManyToManyField(blank=True, related_name='playlist', to='song.song')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_songs',
            field=models.ManyToManyField(related_name='favorited_by', to='song.song'),
        ),
    ]
